export class Paragraphe {

    tacheID:string=''
    last_update:string=''
    user_update:string=''
    ip_update:string=''
    libelleFr:string=''
    libelleUs:string=''
    dateDebut:string=''
    dateFin:string=''
    resultatFr:string=''
    resultatUs:string=''
    indicateurFr:string=''
    indicateurUs:string=''
    sourceVerificationFr:string=''
    sourceVerificationUs:string=''
    CompteCode:string=''
    financementID:string=''
    structureID:string=''
    activiteBudgetiseID:string=''
    posteComptableID:string=''
    ordreDansActivite:string=''
    AEReport:string=''
    CPReport:string=''
    AEInitial:string=''
    CPInitial:string=''
    AEAdditif:string=''
    CPAdditif:string=''
    calendrier:string=''
    numordre:string=''
    abbreviationFr:string=''
    structurelibelle:string=''
    compteLibelle:string=''
    financementLibelle:string=''
    pcLibelle:string=''
    budgetExploite:string=''

}

   